"""init schema

Revision ID: 0001_init_schema
Revises: 
Create Date: 2026-02-13 18:03:15.402714

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0001_init_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', name='uq_continent_nom')
    )
    op.create_table('document_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('document_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_key', name='uq_document_type_key'),
    sa.UniqueConstraint('nom', name='uq_document_type_nom')
    )
    op.create_table('fidele_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', name='uq_fidele_type_nom')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', name='uq_grade_nom')
    )
    op.create_table('paroisse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', name='uq_paroisse_nom')
    )
    op.create_table('structure_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', name='uq_structure_type_nom')
    )
    op.create_index('idx_structure_type_est_supprimee', 'structure_type', ['est_supprimee'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_document_type', sa.Integer(), nullable=False),
    sa.Column('id_document', sa.Integer(), nullable=False),
    sa.Column('tel1', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('tel2', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('whatsapp', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_document_type'], ['document_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contact_document', 'contact', ['id_document_type', 'id_document'], unique=False)
    op.create_index('idx_contact_est_supprimee', 'contact', ['est_supprimee'], unique=False)
    op.create_table('fidele',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('postnom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sexe', sa.Enum('M', 'F', name='gender'), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('est_baptise', sa.Boolean(), nullable=False),
    sa.Column('date_bapteme', sa.Date(), nullable=True),
    sa.Column('numero_carte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('id_grade', sa.Integer(), nullable=False),
    sa.Column('id_fidele_type', sa.Integer(), nullable=False),
    sa.Column('id_paroisse', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_fidele_type'], ['fidele_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_grade'], ['grade.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_paroisse'], ['paroisse.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_carte', name='uq_fidele_numero_carte')
    )
    op.create_index('idx_fidele_est_supprimee', 'fidele', ['est_supprimee'], unique=False)
    op.create_index('idx_fidele_grade', 'fidele', ['id_grade'], unique=False)
    op.create_index('idx_fidele_nom', 'fidele', ['nom'], unique=False)
    op.create_table('fonction_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('id_document_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_document_type'], ['document_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fonction_list_est_supprimee', 'fonction_list', ['est_supprimee'], unique=False)
    op.create_table('nation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_continent', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_continent'], ['continent.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', name='uq_nation_nom')
    )
    op.create_table('structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_structure_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_structure_type'], ['structure_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_structure_est_supprimee', 'structure', ['est_supprimee'], unique=False)
    op.create_table('adresse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_document', sa.Integer(), nullable=False),
    sa.Column('id_nation', sa.Integer(), nullable=False),
    sa.Column('id_document_type', sa.Integer(), nullable=False),
    sa.Column('province_etat', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ville', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('commune', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('avenue', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('adresse_complete', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_document_type'], ['document_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_nation'], ['nation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adresse_document', 'adresse', ['id_document_type', 'id_document'], unique=False)
    op.create_index('idx_adresse_est_supprimee', 'adresse', ['est_supprimee'], unique=False)
    op.create_index('idx_adresse_nation', 'adresse', ['id_nation'], unique=False)
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_structure', sa.Integer(), nullable=False),
    sa.Column('id_document_type', sa.Integer(), nullable=False),
    sa.Column('id_document', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_document_type'], ['document_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_structure'], ['structure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_direction_doc', 'direction', ['id_document_type', 'id_document'], unique=False)
    op.create_index('idx_direction_est_supprimee', 'direction', ['est_supprimee'], unique=False)
    op.create_index('idx_direction_structure', 'direction', ['id_structure'], unique=False)
    op.create_table('fidele_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_adhesion', sa.Date(), nullable=True),
    sa.Column('date_sortie', sa.Date(), nullable=True),
    sa.Column('id_fidele', sa.Integer(), nullable=False),
    sa.Column('id_structure', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fidele'], ['fidele.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_structure'], ['structure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fidele_structure_est_supprimee', 'fidele_structure', ['est_supprimee'], unique=False)
    op.create_index('idx_fidele_structure_fidele', 'fidele_structure', ['id_fidele'], unique=False)
    op.create_index('idx_fidele_structure_structure', 'fidele_structure', ['id_structure'], unique=False)
    op.create_table('direction_fonction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('est_suspendu', sa.Boolean(), nullable=False),
    sa.Column('id_direction', sa.Integer(), nullable=False),
    sa.Column('id_fidele', sa.Integer(), nullable=False),
    sa.Column('id_fonction', sa.Integer(), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_direction'], ['direction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_fidele'], ['fidele.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_fonction'], ['fonction_list.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_direction_fonction_current', 'direction_fonction', ['id_direction', 'est_actif'], unique=False)
    op.create_index('idx_direction_fonction_est_supprimee', 'direction_fonction', ['est_supprimee'], unique=False)
    op.create_index('idx_direction_fonction_fidele', 'direction_fonction', ['id_fidele'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_direction_fonction_fidele', table_name='direction_fonction')
    op.drop_index('idx_direction_fonction_est_supprimee', table_name='direction_fonction')
    op.drop_index('idx_direction_fonction_current', table_name='direction_fonction')
    op.drop_table('direction_fonction')
    op.drop_index('idx_fidele_structure_structure', table_name='fidele_structure')
    op.drop_index('idx_fidele_structure_fidele', table_name='fidele_structure')
    op.drop_index('idx_fidele_structure_est_supprimee', table_name='fidele_structure')
    op.drop_table('fidele_structure')
    op.drop_index('idx_direction_structure', table_name='direction')
    op.drop_index('idx_direction_est_supprimee', table_name='direction')
    op.drop_index('idx_direction_doc', table_name='direction')
    op.drop_table('direction')
    op.drop_index('idx_adresse_nation', table_name='adresse')
    op.drop_index('idx_adresse_est_supprimee', table_name='adresse')
    op.drop_index('idx_adresse_document', table_name='adresse')
    op.drop_table('adresse')
    op.drop_index('idx_structure_est_supprimee', table_name='structure')
    op.drop_table('structure')
    op.drop_table('nation')
    op.drop_index('idx_fonction_list_est_supprimee', table_name='fonction_list')
    op.drop_table('fonction_list')
    op.drop_index('idx_fidele_nom', table_name='fidele')
    op.drop_index('idx_fidele_grade', table_name='fidele')
    op.drop_index('idx_fidele_est_supprimee', table_name='fidele')
    op.drop_table('fidele')
    op.drop_index('idx_contact_est_supprimee', table_name='contact')
    op.drop_index('idx_contact_document', table_name='contact')
    op.drop_table('contact')
    op.drop_index('idx_structure_type_est_supprimee', table_name='structure_type')
    op.drop_table('structure_type')
    op.drop_table('paroisse')
    op.drop_table('grade')
    op.drop_table('fidele_type')
    op.drop_table('document_type')
    op.drop_table('continent')
    # ### end Alembic commands ###
