"""add fidele_paroisse

Revision ID: 02f03a348854
Revises: 0004_seed
Create Date: 2026-02-16 16:13:15.518015

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02f03a348854'
down_revision = '0004_seed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fidele_paroisse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_adhesion', sa.Date(), nullable=True),
    sa.Column('date_sortie', sa.Date(), nullable=True),
    sa.Column('id_fidele', sa.Integer(), nullable=False),
    sa.Column('id_paroisse', sa.Integer(), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_fidele'], ['fidele.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_paroisse'], ['paroisse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fidele_paroisse_est_supprimee', 'fidele_paroisse', ['est_supprimee'], unique=False)
    op.create_index('idx_fidele_paroisse_fidele', 'fidele_paroisse', ['id_fidele'], unique=False)
    op.create_index('idx_fidele_paroisse_paroisse', 'fidele_paroisse', ['id_paroisse'], unique=False)
    op.drop_constraint(op.f('fidele_ibfk_3'), 'fidele', type_='foreignkey')
    op.drop_column('fidele', 'id_paroisse')
    op.drop_column('fidele_structure', 'date_adhesion')
    op.drop_column('fidele_structure', 'date_sortie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fidele_structure', sa.Column('date_sortie', sa.DATE(), nullable=True))
    op.add_column('fidele_structure', sa.Column('date_adhesion', sa.DATE(), nullable=True))
    op.add_column('fidele', sa.Column('id_paroisse', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fidele_ibfk_3'), 'fidele', 'paroisse', ['id_paroisse'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_fidele_paroisse_paroisse', table_name='fidele_paroisse')
    op.drop_index('idx_fidele_paroisse_fidele', table_name='fidele_paroisse')
    op.drop_index('idx_fidele_paroisse_est_supprimee', table_name='fidele_paroisse')
    op.drop_table('fidele_paroisse')
    # ### end Alembic commands ###
