"""apply_remaining_schema_diffs

Revision ID: 14607bbf4981
Revises: d65cf439548b
Create Date: 2026-03-13 03:46:29.057388

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14607bbf4981'
down_revision = 'd65cf439548b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new index first so FK constraint can migrate to it before we drop the old one
    op.create_index('idx_fidele_origine_nation_origine', 'fidele_origine', ['id_nation_origine'], unique=False)
    op.drop_index(op.f('idx_fidele_origine_nation'), table_name='fidele_origine')
    op.alter_column('nation', 'iso_alpha_2',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nation', 'iso_alpha_2',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.drop_index('idx_fidele_origine_nation_origine', table_name='fidele_origine')
    op.create_index(op.f('idx_fidele_origine_nation'), 'fidele_origine', ['id_nation_origine'], unique=False)
    # ### end Alembic commands ###
