"""add fidele's additional fields id_fidele_recenseur, id_nation_nationalite id_etat_civile

Revision ID: 70a6594a2b2d
Revises: cd2278ea8937
Create Date: 2026-02-16 22:16:30.208570

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '70a6594a2b2d'
down_revision = 'cd2278ea8937'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fidele', sa.Column('id_fidele_recenseur', sa.Integer(), nullable=True))
    op.add_column('fidele', sa.Column('id_nation_nationalite', sa.Integer(), nullable=True))
    op.add_column('fidele', sa.Column('id_etat_civile', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fidele', 'etat_civile', ['id_etat_civile'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'fidele', 'nation', ['id_nation_nationalite'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'fidele', 'fidele', ['id_fidele_recenseur'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fidele', type_='foreignkey')
    op.drop_constraint(None, 'fidele', type_='foreignkey')
    op.drop_constraint(None, 'fidele', type_='foreignkey')
    op.drop_column('fidele', 'id_etat_civile')
    op.drop_column('fidele', 'id_nation_nationalite')
    op.drop_column('fidele', 'id_fidele_recenseur')
    # ### end Alembic commands ###
