"""add document_statut

Revision ID: 9be1f9db74bf
Revises: 0003_seed
Create Date: 2026-02-16 15:18:19.968241

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9be1f9db74bf'
down_revision = '0003_seed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_statut',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_document_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_document_type'], ['document_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', 'id_document_type', name='uq_document_statut_nom_doc_type')
    )
    op.create_index('idx_document_statut_est_supprimee', 'document_statut', ['est_supprimee'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document_statut_est_supprimee', table_name='document_statut')
    op.drop_table('document_statut')
    # ### end Alembic commands ###
