"""add file

Revision ID: 9f2a2885b963
Revises: 70a6594a2b2d
Create Date: 2026-02-17 15:28:40.607242

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9f2a2885b963'
down_revision = '70a6594a2b2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mimetype', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('signed_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('signed_url_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_document_type', sa.Integer(), nullable=False),
    sa.Column('id_document', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_document_type'], ['document_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('file_name', name='uq_files_file_name')
    )
    op.create_index('idx_files_document', 'file', ['id_document_type', 'id_document'], unique=False)
    op.create_index('idx_files_est_supprimee', 'file', ['est_supprimee'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_files_est_supprimee', table_name='file')
    op.drop_index('idx_files_document', table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
