"""backfill nation iso_alpha_2

Revision ID: c7f1e2a9d4b3
Revises: b2f4d8c1a101
Create Date: 2026-02-25 16:10:00.000000

"""
from __future__ import annotations

from alembic import op


# revision identifiers, used by Alembic.
revision = "c7f1e2a9d4b3"
down_revision = "b2f4d8c1a101"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Backfill ISO alpha-2 codes for nations based on their names.
    op.execute("UPDATE nation SET iso_alpha_2 = 'AF' WHERE id = 1;")
op.execute("UPDATE nation SET iso_alpha_2 = 'ZA' WHERE id = 2;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AL' WHERE id = 3;")
op.execute("UPDATE nation SET iso_alpha_2 = 'DZ' WHERE id = 4;")
op.execute("UPDATE nation SET iso_alpha_2 = 'DE' WHERE id = 5;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AD' WHERE id = 6;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AO' WHERE id = 7;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AG' WHERE id = 8;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SA' WHERE id = 9;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AM' WHERE id = 10;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AU' WHERE id = 11;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AT' WHERE id = 12;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AZ' WHERE id = 13;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BS' WHERE id = 14;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BH' WHERE id = 15;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BD' WHERE id = 16;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BB' WHERE id = 17;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BE' WHERE id = 18;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BZ' WHERE id = 19;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BJ' WHERE id = 20;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BT' WHERE id = 21;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BY' WHERE id = 22;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MM' WHERE id = 23;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BO' WHERE id = 24;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BA' WHERE id = 25;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BW' WHERE id = 26;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BR' WHERE id = 27;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BN' WHERE id = 28;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BG' WHERE id = 29;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BF' WHERE id = 30;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BI' WHERE id = 31;")
op.execute("UPDATE nation SET iso_alpha_2 = 'KH' WHERE id = 32;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CM' WHERE id = 33;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CA' WHERE id = 34;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CV' WHERE id = 35;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CL' WHERE id = 36;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CN' WHERE id = 37;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CY' WHERE id = 38;")
# op.execute("UPDATE nation SET iso_alpha_2 = NULL WHERE id = 39;") # Chypre du Nord (No ISO Code)
op.execute("UPDATE nation SET iso_alpha_2 = 'CO' WHERE id = 40;")
op.execute("UPDATE nation SET iso_alpha_2 = 'KM' WHERE id = 41;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CG' WHERE id = 42;")
op.execute("UPDATE nation SET iso_alpha_2 = 'KP' WHERE id = 43;")
op.execute("UPDATE nation SET iso_alpha_2 = 'KR' WHERE id = 44;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CR' WHERE id = 45;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CI' WHERE id = 46;")
op.execute("UPDATE nation SET iso_alpha_2 = 'HR' WHERE id = 47;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CU' WHERE id = 48;")
op.execute("UPDATE nation SET iso_alpha_2 = 'DK' WHERE id = 49;")
op.execute("UPDATE nation SET iso_alpha_2 = 'DJ' WHERE id = 50;")
op.execute("UPDATE nation SET iso_alpha_2 = 'DM' WHERE id = 51;")
op.execute("UPDATE nation SET iso_alpha_2 = 'EG' WHERE id = 52;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SV' WHERE id = 53;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AE' WHERE id = 54;")
op.execute("UPDATE nation SET iso_alpha_2 = 'EC' WHERE id = 55;")
op.execute("UPDATE nation SET iso_alpha_2 = 'ER' WHERE id = 56;")
op.execute("UPDATE nation SET iso_alpha_2 = 'ES' WHERE id = 57;")
op.execute("UPDATE nation SET iso_alpha_2 = 'EE' WHERE id = 58;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SZ' WHERE id = 59;")
op.execute("UPDATE nation SET iso_alpha_2 = 'US' WHERE id = 60;")
op.execute("UPDATE nation SET iso_alpha_2 = 'ET' WHERE id = 61;")
op.execute("UPDATE nation SET iso_alpha_2 = 'FJ' WHERE id = 62;")
op.execute("UPDATE nation SET iso_alpha_2 = 'FI' WHERE id = 63;")
op.execute("UPDATE nation SET iso_alpha_2 = 'FR' WHERE id = 64;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GA' WHERE id = 65;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GM' WHERE id = 66;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GE' WHERE id = 67;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GS' WHERE id = 68;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GH' WHERE id = 69;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GI' WHERE id = 70;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GR' WHERE id = 71;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GD' WHERE id = 72;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GL' WHERE id = 73;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GP' WHERE id = 74;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GU' WHERE id = 75;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GT' WHERE id = 76;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GG' WHERE id = 77;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GN' WHERE id = 78;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GQ' WHERE id = 79;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GW' WHERE id = 80;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GY' WHERE id = 81;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GF' WHERE id = 82;")
op.execute("UPDATE nation SET iso_alpha_2 = 'HT' WHERE id = 83;")
op.execute("UPDATE nation SET iso_alpha_2 = 'HN' WHERE id = 84;")
op.execute("UPDATE nation SET iso_alpha_2 = 'HK' WHERE id = 85;")
op.execute("UPDATE nation SET iso_alpha_2 = 'HU' WHERE id = 86;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BV' WHERE id = 87;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CX' WHERE id = 88;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NF' WHERE id = 89;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AX' WHERE id = 90;")
op.execute("UPDATE nation SET iso_alpha_2 = 'FO' WHERE id = 91;")
op.execute("UPDATE nation SET iso_alpha_2 = 'HM' WHERE id = 92;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MP' WHERE id = 93;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PN' WHERE id = 94;")
op.execute("UPDATE nation SET iso_alpha_2 = 'IN' WHERE id = 95;")
op.execute("UPDATE nation SET iso_alpha_2 = 'ID' WHERE id = 96;")
op.execute("UPDATE nation SET iso_alpha_2 = 'IQ' WHERE id = 97;")
op.execute("UPDATE nation SET iso_alpha_2 = 'IR' WHERE id = 98;")
op.execute("UPDATE nation SET iso_alpha_2 = 'IE' WHERE id = 99;")
op.execute("UPDATE nation SET iso_alpha_2 = 'IS' WHERE id = 100;")
op.execute("UPDATE nation SET iso_alpha_2 = 'IL' WHERE id = 101;")
op.execute("UPDATE nation SET iso_alpha_2 = 'IT' WHERE id = 102;")
op.execute("UPDATE nation SET iso_alpha_2 = 'JM' WHERE id = 103;")
op.execute("UPDATE nation SET iso_alpha_2 = 'JP' WHERE id = 104;")
op.execute("UPDATE nation SET iso_alpha_2 = 'JE' WHERE id = 105;")
op.execute("UPDATE nation SET iso_alpha_2 = 'JO' WHERE id = 106;")
op.execute("UPDATE nation SET iso_alpha_2 = 'KZ' WHERE id = 107;")
op.execute("UPDATE nation SET iso_alpha_2 = 'KE' WHERE id = 108;")
op.execute("UPDATE nation SET iso_alpha_2 = 'KG' WHERE id = 109;")
op.execute("UPDATE nation SET iso_alpha_2 = 'KI' WHERE id = 110;")
op.execute("UPDATE nation SET iso_alpha_2 = 'XK' WHERE id = 111;")
op.execute("UPDATE nation SET iso_alpha_2 = 'KW' WHERE id = 112;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LA' WHERE id = 113;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LS' WHERE id = 114;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LV' WHERE id = 115;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LB' WHERE id = 116;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LR' WHERE id = 117;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LY' WHERE id = 118;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LI' WHERE id = 119;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LT' WHERE id = 120;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LU' WHERE id = 121;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MO' WHERE id = 122;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MK' WHERE id = 123;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MG' WHERE id = 124;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MY' WHERE id = 125;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MW' WHERE id = 126;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MV' WHERE id = 127;")
op.execute("UPDATE nation SET iso_alpha_2 = 'ML' WHERE id = 128;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MT' WHERE id = 129;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MA' WHERE id = 130;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MQ' WHERE id = 131;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MU' WHERE id = 132;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MR' WHERE id = 133;")
op.execute("UPDATE nation SET iso_alpha_2 = 'YT' WHERE id = 134;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MX' WHERE id = 135;")
op.execute("UPDATE nation SET iso_alpha_2 = 'FM' WHERE id = 136;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MD' WHERE id = 137;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MN' WHERE id = 138;")
op.execute("UPDATE nation SET iso_alpha_2 = 'ME' WHERE id = 139;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MS' WHERE id = 140;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MZ' WHERE id = 141;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NA' WHERE id = 142;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NR' WHERE id = 143;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NP' WHERE id = 144;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NI' WHERE id = 145;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NE' WHERE id = 146;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NG' WHERE id = 147;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NU' WHERE id = 148;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NO' WHERE id = 149;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NC' WHERE id = 150;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NZ' WHERE id = 151;")
op.execute("UPDATE nation SET iso_alpha_2 = 'OM' WHERE id = 152;")
op.execute("UPDATE nation SET iso_alpha_2 = 'UG' WHERE id = 153;")
op.execute("UPDATE nation SET iso_alpha_2 = 'UZ' WHERE id = 154;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PW' WHERE id = 155;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PS' WHERE id = 156;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PA' WHERE id = 157;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PG' WHERE id = 158;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PK' WHERE id = 159;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PY' WHERE id = 160;")
op.execute("UPDATE nation SET iso_alpha_2 = 'NL' WHERE id = 161;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PE' WHERE id = 162;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PH' WHERE id = 163;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PL' WHERE id = 164;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PF' WHERE id = 165;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PR' WHERE id = 166;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PT' WHERE id = 167;")
op.execute("UPDATE nation SET iso_alpha_2 = 'QA' WHERE id = 168;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CF' WHERE id = 169;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CD' WHERE id = 170;")
op.execute("UPDATE nation SET iso_alpha_2 = 'DO' WHERE id = 171;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CZ' WHERE id = 172;")
op.execute("UPDATE nation SET iso_alpha_2 = 'RE' WHERE id = 173;")
op.execute("UPDATE nation SET iso_alpha_2 = 'RO' WHERE id = 174;")
op.execute("UPDATE nation SET iso_alpha_2 = 'GB' WHERE id = 175;")
op.execute("UPDATE nation SET iso_alpha_2 = 'RU' WHERE id = 176;")
op.execute("UPDATE nation SET iso_alpha_2 = 'RW' WHERE id = 177;")
op.execute("UPDATE nation SET iso_alpha_2 = 'EH' WHERE id = 178;")
op.execute("UPDATE nation SET iso_alpha_2 = 'BL' WHERE id = 179;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SH' WHERE id = 180;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LC' WHERE id = 181;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SM' WHERE id = 182;")
op.execute("UPDATE nation SET iso_alpha_2 = 'MF' WHERE id = 183;")
op.execute("UPDATE nation SET iso_alpha_2 = 'PM' WHERE id = 184;")
op.execute("UPDATE nation SET iso_alpha_2 = 'VC' WHERE id = 185;")
op.execute("UPDATE nation SET iso_alpha_2 = 'KN' WHERE id = 186;")
op.execute("UPDATE nation SET iso_alpha_2 = 'WS' WHERE id = 187;")
op.execute("UPDATE nation SET iso_alpha_2 = 'AS' WHERE id = 188;")
op.execute("UPDATE nation SET iso_alpha_2 = 'ST' WHERE id = 189;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SN' WHERE id = 190;")
op.execute("UPDATE nation SET iso_alpha_2 = 'RS' WHERE id = 191;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SC' WHERE id = 192;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SL' WHERE id = 193;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SG' WHERE id = 194;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SX' WHERE id = 195;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SK' WHERE id = 196;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SI' WHERE id = 197;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SO' WHERE id = 198;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SD' WHERE id = 199;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SS' WHERE id = 200;")
op.execute("UPDATE nation SET iso_alpha_2 = 'LK' WHERE id = 201;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SE' WHERE id = 202;")
op.execute("UPDATE nation SET iso_alpha_2 = 'CH' WHERE id = 203;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SR' WHERE id = 204;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SJ' WHERE id = 205;")
op.execute("UPDATE nation SET iso_alpha_2 = 'SY' WHERE id = 206;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TJ' WHERE id = 207;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TW' WHERE id = 208;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TZ' WHERE id = 209;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TD' WHERE id = 210;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TF' WHERE id = 211;")
op.execute("UPDATE nation SET iso_alpha_2 = 'IO' WHERE id = 212;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TH' WHERE id = 213;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TL' WHERE id = 214;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TG' WHERE id = 215;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TK' WHERE id = 216;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TO' WHERE id = 217;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TT' WHERE id = 218;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TN' WHERE id = 219;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TM' WHERE id = 220;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TR' WHERE id = 221;")
op.execute("UPDATE nation SET iso_alpha_2 = 'TV' WHERE id = 222;")
op.execute("UPDATE nation SET iso_alpha_2 = 'UA' WHERE id = 223;")
op.execute("UPDATE nation SET iso_alpha_2 = 'UY' WHERE id = 224;")
op.execute("UPDATE nation SET iso_alpha_2 = 'VU' WHERE id = 225;")
op.execute("UPDATE nation SET iso_alpha_2 = 'VE' WHERE id = 226;")
op.execute("UPDATE nation SET iso_alpha_2 = 'VN' WHERE id = 227;")
op.execute("UPDATE nation SET iso_alpha_2 = 'WF' WHERE id = 228;")
op.execute("UPDATE nation SET iso_alpha_2 = 'YE' WHERE id = 229;")
op.execute("UPDATE nation SET iso_alpha_2 = 'ZM' WHERE id = 230;")
op.execute("UPDATE nation SET iso_alpha_2 = 'ZW' WHERE id = 231;")

def downgrade() -> None:
    # Intentionnellement no-op: ne pas effacer des données de référence déjà normalisées.
    pass
