"""add fidele_occupation

Revision ID: cd2278ea8937
Revises: fdf50964dbc5
Create Date: 2026-02-16 18:18:17.405391

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cd2278ea8937'
down_revision = 'fdf50964dbc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fidele_occupation',
    sa.Column('ecole_universite_employeur', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_fidele', sa.Integer(), nullable=False),
    sa.Column('id_niveau_etude', sa.Integer(), nullable=False),
    sa.Column('id_profession', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fidele'], ['fidele.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_niveau_etude'], ['niveau_etudes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_profession'], ['profession.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_fidele', name='uq_fidele_occupation_fidele')
    )
    op.create_index('idx_fidele_occupation_est_supprimee', 'fidele_occupation', ['est_supprimee'], unique=False)
    op.create_index('idx_fidele_occupation_fidele', 'fidele_occupation', ['id_fidele'], unique=False)
    op.create_index('idx_fidele_occupation_niveau', 'fidele_occupation', ['id_niveau_etude'], unique=False)
    op.create_index('idx_fidele_occupation_profession', 'fidele_occupation', ['id_profession'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fidele_occupation_profession', table_name='fidele_occupation')
    op.drop_index('idx_fidele_occupation_niveau', table_name='fidele_occupation')
    op.drop_index('idx_fidele_occupation_fidele', table_name='fidele_occupation')
    op.drop_index('idx_fidele_occupation_est_supprimee', table_name='fidele_occupation')
    op.drop_table('fidele_occupation')
    # ### end Alembic commands ###
