"""add_recensement_etape_and_fidele_recensement_etape

Revision ID: d65cf439548b
Revises: 6ab1e2d3f4c5
Create Date: 2026-03-13 03:12:54.243984

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd65cf439548b'
down_revision = '6ab1e2d3f4c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Guard against partial runs (MySQL non-transactional DDL)
    op.execute("DROP TABLE IF EXISTS fidele_recensement_etape")
    op.execute("DROP TABLE IF EXISTS recensement_etape")
    op.create_table('recensement_etape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', name='uq_recensement_etape_nom')
    )
    op.create_table('fidele_recensement_etape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_fidele', sa.Integer(), nullable=False),
    sa.Column('id_recensement_etape', sa.Integer(), nullable=False),
    sa.Column('id_document_statut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_document_statut'], ['document_statut.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_fidele'], ['fidele.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_recensement_etape'], ['recensement_etape.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_fidele', 'id_recensement_etape', name='uq_fidele_recensement_etape')
    )
    op.create_index('idx_fidele_recensement_etape_etape', 'fidele_recensement_etape', ['id_recensement_etape'], unique=False)
    op.create_index('idx_fidele_recensement_etape_fidele', 'fidele_recensement_etape', ['id_fidele'], unique=False)
    op.create_index('idx_fidele_recensement_etape_statut', 'fidele_recensement_etape', ['id_document_statut'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fidele_recensement_etape_statut', table_name='fidele_recensement_etape')
    op.drop_index('idx_fidele_recensement_etape_fidele', table_name='fidele_recensement_etape')
    op.drop_index('idx_fidele_recensement_etape_etape', table_name='fidele_recensement_etape')
    op.drop_table('fidele_recensement_etape')
    op.drop_table('recensement_etape')
    # ### end Alembic commands ###
