"""add fidele_baptem fidele_famille fidele_origine

Revision ID: fdf50964dbc5
Revises: 02f03a348854
Create Date: 2026-02-16 17:00:58.292097

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fdf50964dbc5'
down_revision = '02f03a348854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fidele_bapteme',
    sa.Column('date_bapteme', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_fidele', sa.Integer(), nullable=False),
    sa.Column('id_paroisse', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_fidele'], ['fidele.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_paroisse'], ['paroisse.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_fidele', name='uq_fidele_bapteme_fidele')
    )
    op.create_index('idx_fidele_bapteme_est_supprimee', 'fidele_bapteme', ['est_supprimee'], unique=False)
    op.create_index('idx_fidele_bapteme_fidele', 'fidele_bapteme', ['id_fidele'], unique=False)
    op.create_index('idx_fidele_bapteme_paroisse', 'fidele_bapteme', ['id_paroisse'], unique=False)
    op.create_table('fidele_famille',
    sa.Column('nom_conjoint', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('postnom_conjoint', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('prenom_conjoint', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('nombre_enfants', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_fidele', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fidele'], ['fidele.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_fidele', name='uq_fidele_famille_fidele')
    )
    op.create_index('idx_fidele_famille_est_supprimee', 'fidele_famille', ['est_supprimee'], unique=False)
    op.create_index('idx_fidele_famille_fidele', 'fidele_famille', ['id_fidele'], unique=False)
    op.create_table('fidele_origine',
    sa.Column('village', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('groupement', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('secteur', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('territoire', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('est_supprimee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_fidele', sa.Integer(), nullable=False),
    sa.Column('id_nation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_fidele'], ['fidele.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_nation'], ['nation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_fidele', name='uq_fidele_origine_fidele')
    )
    op.create_index('idx_fidele_origine_est_supprimee', 'fidele_origine', ['est_supprimee'], unique=False)
    op.create_index('idx_fidele_origine_fidele', 'fidele_origine', ['id_fidele'], unique=False)
    op.create_index('idx_fidele_origine_nation', 'fidele_origine', ['id_nation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fidele_origine_nation', table_name='fidele_origine')
    op.drop_index('idx_fidele_origine_fidele', table_name='fidele_origine')
    op.drop_index('idx_fidele_origine_est_supprimee', table_name='fidele_origine')
    op.drop_table('fidele_origine')
    op.drop_index('idx_fidele_famille_fidele', table_name='fidele_famille')
    op.drop_index('idx_fidele_famille_est_supprimee', table_name='fidele_famille')
    op.drop_table('fidele_famille')
    op.drop_index('idx_fidele_bapteme_paroisse', table_name='fidele_bapteme')
    op.drop_index('idx_fidele_bapteme_fidele', table_name='fidele_bapteme')
    op.drop_index('idx_fidele_bapteme_est_supprimee', table_name='fidele_bapteme')
    op.drop_table('fidele_bapteme')
    # ### end Alembic commands ###
