"""Textes de documentation (OpenAPI) pour les endpoints Direction.

But: garder les routers lisibles en isolant les descriptions longues.
"""

DIRECTION_CREATE_DESCRIPTION = (
    "Une **direction** représente l'instance qui dirige une **structure** (Bureau ecclésiastique, Mouvement, Association, Service, etc.) "
    "à un **échelon ecclésiastique** donné.\n\n"
    "### Comment représenter l'échelon ?\n"
    "L'échelon ecclésiastique est modélisé par le couple :\n"
    "- `id_document_type` : référence vers `document_type.id` (ex: PAROISSE, NATION, ...)\n"
    "- `id_document` : l'ID du document cible dans la table correspondante (ex: `paroisse.id`, `nation.id`, ...)\n\n"
    "### Exemple (GTKI paroissiale)\n"
    "Objectif: créer la direction **paroissiale** de la chorale/mouvement *GTKI*.\n\n"
    "1) **Vérifier la structure**\n"
    "- La structure *GTKI* doit exister dans `structure` et être de type *mouvement* (ex: `id_structure_type = 2`).\n"
    "- Si elle n'existe pas, la créer d'abord via `POST /constant/structure`.\n\n"
    "2) **Vérifier la paroisse**\n"
    "- La paroisse doit exister dans `paroisse`.\n"
    "- Sinon, la créer via `POST /paroisse`.\n\n"
    "3) **Créer la direction** (cet endpoint)\n"
    "- `id_structure` = ID de la structure GTKI\n"
    "- `id_document_type` = ID du type de document **PAROISSE** (venant de `/constant/document_type`)\n"
    "- `id_document` = ID de la paroisse cible\n\n"
    "Exemple de payload:\n"
    "```json\n"
    "{\n"
    "  \"id_structure\": 12,\n"
    "  \"id_document_type\": 2,\n"
    "  \"id_document\": 7,\n"
    "  \"nom\": \"Direction paroissiale - GTKI / Paroisse X\"\n"
    "}\n"
    "```\n\n"
    "### Variante (direction nationale)\n"
    "Pour une direction **nationale** de GTKI :\n"
    "- `id_document_type` = ID du type **NATION**\n"
    "- `id_document` = ID de la nation (venant de `/constant/nation`)\n\n"
    "### Attacher des fidèles à la direction (mandats / fonctions)\n"
    "Une fois la direction créée, pour **attacher des fidèles** au projet (bureau), il faut créer des mandats "
    "via : `POST /direction/{id}/fonctions`\n"
    "Payload attendu (exemple) :\n"
    "```json\n"
    "{\n"
    "  \"id_fidele\": 101,\n"
    "  \"id_fonction\": 3,\n"
    "  \"date_debut\": \"2026-01-01\",\n"
    "  \"date_fin\": null,\n"
    "  \"est_suspendu\": false\n"
    "}\n"
    "```\n"
)
